### ISSUE TITLE
Asynchronous authentication in onUpgrade is potentially dangerous

### ISSUE THREAD

**Issue by wshamp** [MihaelIsaev/WS#1]
A client will already have a websocket connection at this point and could be sending messages that would be ignored if success hasn't been called yet or am I missing something?

**Comment by wshamp** [comment]
I have brought this issue up on vapor discord and this issue is the result of that conversation: https://github.com/apple/swift-nio/issues/699

you can follow that or comment on it as well to hopefully increase the priority on this in their eyes.  In my opinion this is kind of a big issue and makes websockets, at least for me, unusable on Vapor as I need authentication.

**Comment by MihaelIsaev** [comment]
@wshamp it is finally resolved with new Vapor4 version 🙂 🎉
